<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYE40ycP\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYE40ycP/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerYE40ycP.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerYE40ycP\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerYE40ycP\App_KernelProdContainer([
    'container.build_hash' => 'YE40ycP',
    'container.build_id' => '67ef8448',
    'container.build_time' => 1580191540,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYE40ycP');
