<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPydOQLH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPydOQLH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPydOQLH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPydOQLH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPydOQLH\App_KernelDevDebugContainer([
    'container.build_hash' => 'PydOQLH',
    'container.build_id' => '667c5a64',
    'container.build_time' => 1580356396,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPydOQLH');
